-- sdfsdfsdfsdfsdf
vim.loader.enable()
-- Basic config
require("core.mappings")
require("core.ru_mappings")
require("core.plugins")
require("core.colors")
require("core.configs")
require("core.utils")
require("core.autocmd")

-- Plugins config
require("plugins.telescope")
require("plugins.lsp.lsp")
-- require("plugins.lsp.volar")
require("plugins.mason")
require("plugins.cmp")
require("plugins.nullls")
require("plugins.lualine")
require("plugins.treesitter")
require("plugins.toggleterm")
require("plugins.comments")
-- require("plugins.autotag")
require("plugins.buffline")
require("plugins.neotree")
require("plugins.dashboard")
require("plugins.whichkey")
-- require("plugins.zen-mode")
require("plugins.gitsigns")
require("plugins.indent")
